### ISSUE TITLE
Requirements.txt - beautifulsoup4 instead of bs4

### ISSUE THREAD

**Issue by KatjaGlassConsulting** [cdisc-org/usdm#64]
Hi, could you update the requirements.txt to use directly beautifulsoup4, e.g. beautifulsoup4 4.12.3 instead of bs4? the bs4 is just a dummy package designed to prevent namesquatting on PyPI (https://pypi.org/project/bs4/).

**Comment by daveih** [comment]
Will do

**Comment by dih-cdisc** [comment]
Included within v0.53.0
